In [16]:
from pathlib import Path
import pandas as pd

In [17]:
OUTPUT_ROOT = Path("../data/outputs")

files = list(OUTPUT_ROOT.rglob("egg_prediction.csv"))

print(f"Files found: {len(files)}")

Files found: 15

In [18]:
dfs = []

for file in files:
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

print(f"Total rows: {len(df)}")
df.head()

Total rows: 243000

,farm_id,house_number,cage_id,capture_date,processing_date,image_name,image_path,image_size_bytes,egg_count,confidence,registered_model_name,model_version,model_alias,model_synchronized_at,inference_started_at,inference_duration_ms,inference_status,error_message
0,farm_01,1,1000,2026-08-01,2026-08-01,cage_1000.jpg,/data/images/farm_01/house_01/2026/08/01/cage_...,376787,0.0,NaN,egg_counter,4,production,2026-08-01T08:00:00+00:00,2026-08-01T11:00:00+00:00,150,SUCCESS,NaN
1,farm_01,1,1001,2026-08-01,2026-08-01,cage_1001.jpg,/data/images/farm_01/house_01/2026/08/01/cage_...,211161,1.0,0.928573,egg_counter,4,production,2026-08-01T08:00:00+00:00,2026-08-01T11:00:00.050000+00:00,219,SUCCESS,NaN
2,farm_01,1,1002,2026-08-01,2026-08-01,cage_1002.jpg,/data/images/farm_01/house_01/2026/08/01/cage_...,349258,0.0,NaN,egg_counter,4,production,2026-08-01T08:00:00+00:00,2026-08-01T11:00:00.100000+00:00,103,SUCCESS,NaN
3,farm_01,1,1003,2026-08-01,2026-08-01,cage_1003.jpg,/data/images/farm_01/house_01/2026/08/01/cage_...,559898,1.0,0.906637,egg_counter,4,production,2026-08-01T08:00:00+00:00,2026-08-01T11:00:00.150000+00:00,219,SUCCESS,NaN
4,farm_01,1,1004,2026-08-01,2026-08-01,cage_1004.jpg,/data/images/farm_01/house_01/2026/08/01/cage_...,287414,1.0,0.953792,egg_counter,4,production,2026-08-01T08:00:00+00:00,2026-08-01T11:00:00.200000+00:00,81,SUCCESS,NaN

In [19]:
df["inference_status"].value_counts(dropna=False)

SUCCESS    242301
ERROR         699
Name: inference_status, dtype: int64

In [20]:
df["inference_status"].value_counts(
    dropna=False,
    normalize=True
) * 100

SUCCESS    99.712346
ERROR       0.287654
Name: inference_status, dtype: float64

In [21]:
pd.crosstab(
    df["farm_id"],
    df["inference_status"],
    margins=True
)

inference_status  ERROR  SUCCESS     All
farm_id
farm_01             247    82753   83000
farm_02             209    74791   75000
farm_03             243    84757   85000
All                 699   242301  243000